name: Deploy to Oracle

on:
  push:
    branches:
      - test-ci

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/test-ci-image:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/test-ci-image:latest
    
    - name: Copy files to target VM
      run:  scp -r ./kubernetes ${{ secrets.ORACLE_USER }}@${{ secrets.ORACLE_HOST }}:/home/${{ secrets.ORACLE_USER }}

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.ORACLE_HOST }}
        username: ${{ secrets.ORACLE_USER }}
        key: ${{ secrets.ORACLE_SSH_KEY }}
        script: |
          export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          ls -la
          echo "pwd: " | pwd
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/test-ci-image:latest
          docker stop test-ci-image || true
          docker rm test-ci-image || true
          docker run -d -p 8080:8080 --name test-ci-image ${{ secrets.DOCKERHUB_USERNAME }}/test-ci-image:latest